# Generated by Django 4.2.4 on 2024-12-08 11:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('track', models.CharField(max_length=255)),
                ('job_interest', models.CharField(max_length=255)),
                ('cv_url', models.TextField()),
                ('visits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Recrutier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('days', models.IntegerField()),
                ('members', models.IntegerField()),
                ('code', models.IntegerField(unique=True)),
                ('scanned_counts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobscanner.attendee')),
                ('recrutier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_logs', to='jobscanner.recrutier')),
            ],
        ),
    ]
