# Generated by Django 4.2.4 on 2024-12-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobscanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='age',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='location',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
