# Generated by Django 4.2.4 on 2024-12-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobscanner', '0002_attendee_age_attendee_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='linkedin',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
