# Generated by Django 4.2.4 on 2024-12-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobscanner', '0003_attendee_linkedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recrutier',
            name='days',
        ),
        migrations.RemoveField(
            model_name='recrutier',
            name='email',
        ),
        migrations.RemoveField(
            model_name='recrutier',
            name='members',
        ),
        migrations.AddField(
            model_name='recrutier',
            name='job_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recrutier',
            name='rep_name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
