# Generated by Django 4.2.4 on 2024-12-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobscanner', '0004_remove_recrutier_days_remove_recrutier_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='job_interest',
        ),
    ]
